# Gradle performance
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Build reproducibility / CI friendliness
org.gradle.configuration-cache.problems=warn
